### ISSUE TITLE
expose/access position

### ISSUE THREAD

**Issue by eleumik** [mateuszmarkowski/jQuery-Seat-Charts#11]
Hi, thanks for this nice piece of software, super accessible !

is there any way to get the position (row, column) of a cell ? 

I did some changes for reading it but maybe it was already there ? Otherwise I could do a pull request with the changes.

Thanks
Michele

**Comment by mateuszmarkowski** [comment]
Hi Michele, I'm glad you like it.

Row and column information is exposed in the settings object:
```javascript
$('#seat-map').seatCharts().get('3_5').settings.row
$('#seat-map').seatCharts().get('3_5').settings.column
```

**Comment by eleumik** [comment]
Thank you !
