### ISSUE TITLE
Question: "curved" rows?

### ISSUE THREAD

**Issue by gpluess** [mateuszmarkowski/jQuery-Seat-Charts#13]
Hi, just wanted to ask if it is possible to make "curved" rows with this plugin? Like this: http://www.conceptdraw.com/How-To-Guide/picture/building-drawing-software-tools-for-design-elements-seating-plan/Cinema-Theater-seating-plan.png

**Comment by mateuszmarkowski** [comment]
Hi, I think it should be possible with some CSS effort. This is what I achieved by applying margin-top to left- and right-most seats also increasing row height:

![image](https://cloud.githubusercontent.com/assets/5392286/8612881/4bf2d3da-26d8-11e5-8677-4cc5da69e275.png)

**Comment by gpluess** [comment]
Thx. I had to implement an other solution. Nevertheless a nice plugin, thank you!
