### ISSUE TITLE
Question: load different seat charts from different buttons?

### ISSUE THREAD

**Issue by sqrg** [mateuszmarkowski/jQuery-Seat-Charts#14]
In the source of http://jsc.mm-lamp.com/, in line 41 there is this
```
$(document).ready(function() {
```

which I changed to
```
function loadMap(map_array, col_array, row_array) {
```

so that I can load different maps from different buttons. The first time I call the function it works perfectly, but if I click the second button, it doesn't do anything. I've tried the following without success

```
function loadMap(map_array, col_array, row_array) {
    $('#seat-map').html("")
```

Any ideas?

I know this isn't an issue with your code, but I was wondering if you had any idea to implement what I'm trying. Also, sorry for my english

**Comment by mateuszmarkowski** [comment]
Hmm, I haven't tested reloading maps in the same container (div), but I think it should work just fine if you dynamically (upon a button click) create a new container (div) for each map. Would it work for you?

**Comment by sqrg** [comment]
Yes, that would work too. Haven't try it yet
