### ISSUE TITLE
Reloading the map in the same div overlaps with current values

### ISSUE THREAD

**Issue by geniustaha** [mateuszmarkowski/jQuery-Seat-Charts#15]
Hi,
Thanks for the great plugin.
We have different booked seats for different time slots. The user can click on each time slot. The data is fetched via ajax from. 
The first click shows proper result. However, when we click on the next time slot, the booked seats of previous slots and this slots overlap with each other. 
Please suggest what to do. 
Thanks

**Comment by mateuszmarkowski** [comment]
Hi, could you please paste some code snippets so I can try to replicate it?

**Comment by geniustaha** [comment]
Hi,

Thank you so much for the quick response.

I am integrating it with Woocommerce (Wordpress).

Link: http://bit.ly/1J9QlhH

To recreate the issue, from the calendar, select the date as 21st. (I have added data for this.)
Now, click on 9:00 pm. It loads few blocked seats for that time slot. If you click on 3:00 am now, it does not refresh the layout. It does not even allow to select the available seats.
If we refresh the page now, and click 3:00 am first, then it shows available seats. 
However, I would like to change the behaviour as, it should refresh for each time slot selection or date selection. 

If you need FTP details, I can share with you.

Thanks again.

**Comment by mateuszmarkowski** [comment]
If you want to load a different map every time, then you will need to use different div containers. Using the same div is currently not supported.

Yet if you merely want to mark seats as taken, there's no nead to call .seatChars again, you just use selector metods together with .status()

**Comment by geniustaha** [comment]
Hi,
Thank you so much for the direction. Yes, I dont have to load the seat map again. I need to query only booked seat.
sc.find('unavailable').status('available');//to make all the seats available and to flush out previous blocked.
sc.get($var_booked).status('unavailable');//to block the current seats.
