### ISSUE TITLE
How do I override the ID and Label per seats? 

### ISSUE THREAD

**Issue by jmaicaaan** [mateuszmarkowski/jQuery-Seat-Charts#16]
I've been finding ways past few weeks how to I override the ID and the Label. I ended up concatenating it something like this : s = character of the seat
s + "[" + ID + "," + LabelText + "]"
is there another way to do it?

**Comment by mateuszmarkowski** [comment]
This is one way to override IDs and labels. The other one would be using getId and getLabel callbacks. These functions are called for each seat giving you the option to return your own label/ID based on passed params (character, row, column).

**Comment by jmaicaaan** [comment]
Can you provide an example overriding the IDs and labels on each seat.

**Comment by mateuszmarkowski** [comment]
Sure, here's one:

```javascript
//IDs and labels which you want to override
var labels_ids = {
	//key is basically row + '_' + column, so we can easily lookup those from getLabel/getId
	'1_1' : ['NEW_ID', 'L'],
	'3_4' : ['ANOTHER_ID', 'B']
};

//then in seatCharts setup hash:
naming : {
	top : false,
	getLabel : function (character, row, column) {
		//build a pair, so we can look it up in our labels_ids hash
		var pair = row+'_'+column;
		
		//if we have this pair in our hash, override
		if (pair in labels_ids) {
			return labels_ids[pair][1];
		//if not, return default label
		} else {
			return character;
		}
	},
	getId : function (character, row, column) {
		var pair = row+'_'+column;
		
		if (pair in labels_ids) {
			return labels_ids[pair][0];
		} else {
			return character;
		}
	}
}
```

**Comment by jmaicaaan** [comment]
Thans man! I got it already :)

**Comment by Micnick** [comment]
Hi, How get the label on Click Event?

**Comment by jmaicaaan** [comment]
Try doing it <pre> this.settings.label </pre>

**Comment by Micnick** [comment]
Tanks,
