### ISSUE TITLE
Saving selected seats to DB

### ISSUE THREAD

**Issue by JFlindt** [mateuszmarkowski/jQuery-Seat-Charts#21]
First of all ... Thanks!

This is a great piece of code and it works really well.

I am however having some trouble saving the selected seats to a MySQL database.
It is not a issue in the traditional order but would appreciate any input or tips.

Thanks

**Comment by JFlindt** [comment]
Found a solution by making an array and pushing the seats to the array using:
```javascript
var reserve = [];
...
reserve.push(this.data().category+' # '+this.settings.label);
document.getElementById('seats').value = reserve;
```
Then I use a hidden field in my form to send to my php script:
```php
<input type="hidden" name="seats" id="seats" value="" />
```

**Comment by sitrsh12** [comment]
Hi dear i tried a lot.. but couldn't figure out.. could u please send me more on how to do this.. As I'm new to JS.. Thanks in advance
