### ISSUE TITLE
is this library under development yet ? 

### ISSUE THREAD

**Issue by eveevans** [mateuszmarkowski/jQuery-Seat-Charts#22]
I see a lot of pull request and issues growing, But the last commit was on October 2014... (more than one year ago). 

Is this library under development yet? or should I go with other ? 
Is there an updated fork ?

Any update ? @mateuszmarkowski

**Comment by mateuszmarkowski** [comment]
The current version is stable and there are no planned updates.

**Comment by eveevans** [comment]
Thanks.
