### ISSUE TITLE
Irregular seat layouts

### ISSUE THREAD

**Issue by geniustaha** [mateuszmarkowski/jQuery-Seat-Charts#26]
Hi,

Thank you so much for a wonderful code.

Is it possible to create irregular seat layouts. Our rows and columns are not regular.
Example:
a1,a2,a3
b2,b3,b4

Is it possible to do this with the present code?

Please advise.

Thanks and best wishes,

**Comment by mateuszmarkowski** [comment]
That sounds like a great feature but unfortunately it's not supported by JSC.
