### ISSUE TITLE
Orientation Map Css

### ISSUE THREAD

**Issue by rikuhen** [mateuszmarkowski/jQuery-Seat-Charts#28]
Hi, exist some method to change the orientation of the map? (sorry my english)

**Comment by mateuszmarkowski** [comment]
Generally is up to how you define your seats so nothing stops you from building a horizontal map. The demo map is vertical but you could easily change it with a map like this:
aaaaaaaaaa
aaaaaaaaaa  
aa________            [ FRONT  ]
aaaaaaaaaa  
aaaaaaaaaa

**Comment by rikuhen** [comment]
Oh thanks
