### ISSUE TITLE
Click event not being updated when status is changed.

### ISSUE THREAD

**Issue by nayumtamboli** [mateuszmarkowski/jQuery-Seat-Charts#29]
I am defining seat click events at character levels, When I change the status of a seat to another character and then click on that seat, click event of old character is fired and not of the updated on.

Say A is available and B is unavailable, A has ClickA and B has ClickB. For seat id 1, character is A and status is available, After some logic, I update status of seat 1 as unavailable (Using method sc.status(seatid, status)), Now if I click on seat 1, it fires ClickA instead of ClickB. 
Any thoughts? Can you guide me to the solution on this?

**Comment by mateuszmarkowski** [comment]
Hmm, I'm not sure if I understand you correctly. You're saying that you change character of a seat upon a click? Generally characters are constant and only statuses change. Callbacks for characters should remain the same, you can handle your status-dependent logic in callbacks:

```javascript
        click: function () {
            if (this.status() == 'available') {
                //do some stuff, i.e. add to the cart
                return 'selected';
            } else if (this.status() == 'selected') {
                //seat has been vacated
                return 'available';
            } else if (this.status() == 'unavailable') {
                //seat has been already booked
                return 'unavailable';
            } else {
                return this.style();
            }
        }
```

**Comment by nelson6e65** [comment]
There is a way to run a function _after_ the user clicks?

If I run `sc.find('selected').length` it returns old count. I meant not using a manual counter of each state.

`onClicked` or `onSelected` event like,
