### ISSUE TITLE
Update method

### ISSUE THREAD

**Issue by berkandirim** [mateuszmarkowski/jQuery-Seat-Charts#31]
Is there an update method that will update the current options?

I'm getting the seat plan input from the user as leftCol rightCol and rowNum, so user for example can create aa_aaa with 2 and 3 or a_aa with 1 and 2 and so on.

When user clicks on submit I need to be able to update the plan accordingly.

**Comment by mateuszmarkowski** [comment]
No, currently there's no update option like that. I think the safest solution will be to get rid of the map container and create a new div for the new map.

**Comment by berkandirim** [comment]
It doesn't work. I need to somehow dump all the data plugin created. When I create a new map the numbers continue from where the old one left.

**Comment by berkandirim** [comment]
Ok I've managed to do that also.
