### ISSUE TITLE
I find a Bug?

### ISSUE THREAD

**Issue by jerviscui** [mateuszmarkowski/jQuery-Seat-Charts#32]
Who can help me? 
_I'm a Chinese, so my english perhaps no good..., I'm sorry about that._

**The Question:**
I have download the lastest release version.
I use the status() method, like this:
`sc.status(['2_15', '2_10'], 'available');`
and then, when the mouse over the seat `<div/>`, the seat is break down!
I see the html, status() is called after, the seat classes lost the avaliable class style, so I see the .js source file, I find the bug:  on jquery.seat-charts.js line No.123
> //if nothing changes, do nothing
> if (newStyle == oldStyle) {
>     return;
> }

To begin with, I want to contact the master, bug I don't know how to do, and I'm not in this repository so I can't fix it.

### And then, I found the jQuery-Seat-Charts repository code, you fixed the problem already. Can you update the release for others?
@mateuszmarkowski

**Comment by mateuszmarkowski** [comment]
Thanks for pointing that out! I've added a release with that bug fix.

**Comment by jerviscui** [comment]
:+1:
