### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by jatin222** [mateuszmarkowski/jQuery-Seat-Charts#33]
I am new here
So how can I install this.

**Comment by computerwizjared** [comment]
This isn't an application to be installed, it is simply a library for developers to use in their applications. To add it to your code, refer to the documentation in the README.

**Comment by XDRosenheim** [comment]
As @computerwizjared said, no, this is not "installed", but it is "implemented" somehow and some people might not know how to do that.
It is quite simple actually.
**IF** you want to use the stylesheet (CSS) from this, just add if to the header of the site.

```
<head>
  <link rel="stylesheet" type="text/css" href="jQuery-Seat-Charts/jquery.seat-charts.css">
  ....
</head>
```

Add a `<div id="SomeIdThatYouChoose">` tag where you want the chart to be.  
In the end of your body add the `.js`.

```
<body>
  ....
  <div id="seat-map"></div>
  ....
  <script type="text/javascript" src="jQuery-Seat-Charts/jquery.seat-charts.min.js"></script>
  <script type="text/javascript">
  $(document).ready(function() {
    var sc = $('#seat-map').seatCharts({
    ....
```

**Comment by EarlYan** [comment]
you can read the demo, do what the demo do
