### ISSUE TITLE
json format

### ISSUE THREAD

**Issue by kristianwelsh** [mateuszmarkowski/jQuery-Seat-Charts#35]
Can someone please show me an example of how the unavailable seats array should be formatted to load via ajax.

Thanks

**Comment by mateuszmarkowski** [comment]
I'm afraid that this is not a feature of JSC but rather something that you have to implement on your own using [Selector](https://github.com/mateuszmarkowski/jQuery-Seat-Charts#selectors) and [Set](https://github.com/mateuszmarkowski/jQuery-Seat-Charts#set-methods) methods plus AJAX implementation of your choice.
