### ISSUE TITLE
Skip underscore (_) id iteration

### ISSUE THREAD

**Issue by AllRaDiO** [mateuszmarkowski/jQuery-Seat-Charts#38]
JS should skip seat id, row and column iteration while using underscore (no seat)

**Comment by mateuszmarkowski** [comment]
Can you please provide a code snippet which can help replicate the issue?

**Comment by AllRaDiO** [comment]
![default](https://cloud.githubusercontent.com/assets/3577344/18228603/92c3a7ee-725e-11e6-9df4-daeab7475f7c.PNG)

![default](https://cloud.githubusercontent.com/assets/3577344/18228606/a4f788c2-725e-11e6-84ca-c470bcd40cd0.PNG)

Script doesn't ignore "_" (spacer) and increases an ID

**Comment by skshiva** [comment]
Even I am having the same issue... is there any way where it can be ignored....

**Comment by mateuszmarkowski** [comment]
Can you please provide a code snippet which can help replicate the issue?

**Comment by skshiva** [comment]
I solved the issue provide me your email address will mail it to you..... the thing is i am using codeigniter framework for my project... for that i needed this and its getting very hard to integrate this...

**Comment by jaycer17** [comment]
can someone provide the fix for this one?

**Comment by Cokejiang** [comment]
Very need solutions to this problem, some people can help answer it, thank you
