### ISSUE TITLE
How can i put the number of seats according to my mysql variable

### ISSUE THREAD

**Issue by souzaallanxz** [mateuszmarkowski/jQuery-Seat-Charts#46]
How can i integrate this code with my mysql database.
I mean, i want to made, like a for, and my map seats, will have the number of seats that is in some variable in my database.

Thanks!

**Comment by mateuszmarkowski** [comment]
I'm afraid that this is not a relevant question about JSC.

**Comment by XDRosenheim** [comment]
_I know this issue is closed, but I think I might be able to help you a little._

> Please note: number of columns must be equal in each row.

In your database, store the width of your seatmap and the FULL seatmap string. Then you can just split the string according to the width.
