### ISSUE TITLE
merging the seats

### ISSUE THREAD

**Issue by mhesari20** [mateuszmarkowski/jQuery-Seat-Charts#47]
hi. actually it's a suggestion. i'm using JSC to map rooms of a festival. users will select their room on the map. now there are rooms with different  size. rooms like to merged 2 of normal rooms, vertically or horizontally.
sorry for my bad English.
I'll be happy to know your opinion.
thank you.

**Comment by mhesari20** [comment]
something like this link:
http://www.jqueryscript.net/demo/Excel-style-Table-Cell-Selector-Plugin-With-jQuery-TableCellsSelection/

**Comment by mateuszmarkowski** [comment]
Thank you, it's a very interesting suggestion. Merged seats could be a good candidate for some future enhancement of JSC.
