### ISSUE TITLE
Need the 'id' also in the white spaces ('_')

### ISSUE THREAD

**Issue by marcosicp** [mateuszmarkowski/jQuery-Seat-Charts#48]
Hi, I need to have id also in underscores white spaces ('_') because I need to work with that when the map complete renders. Do you know where I need to change @mateuszmarkowski ? I think is in:
$row.append(character != '_' ?
					//if the character is not an underscore (empty space)
					(function (naming) {

					    //so users don't have to specify empty objects
					    settings.seats[character] = character in settings.seats ? settings.seats[character] : {};

					    var id = overrideId ? overrideId : naming.getId(character, naming.rows[row], naming.columns[column]);
					    seats[id] = new seat({
					        id: id,
					        label: overrideLabel ?
					            overrideLabel : naming.getLabel(character, naming.rows[row], naming.columns[column]),
					        row: row,
					        column: column,
					        character: character
					    });

					    seatIds.push(id);
					    return seats[id].node();

					})(settings.naming) :
					//this is just an empty space (_)
					$('<div></div>').addClass('seatCharts-cell seatCharts-space') ////  Here???
				);

Thanks!

**Comment by mateuszmarkowski** [comment]
Yes, I think you found the right place, sorry for a late response.

**Comment by marcosicp** [comment]
I did it thanks @mateuszmarkowski
