### ISSUE TITLE
Update map dimentions from click button

### ISSUE THREAD

**Issue by marcosicp** [mateuszmarkowski/jQuery-Seat-Charts#49]
Hi, there is a way to update the map model from new json after click event?
Because I have 2 buttons one to add columns and other to add rows so I need to re bind it.

Thanks in advance! Regards. @mateuszmarkowski

**Comment by mateuszmarkowski** [comment]
Please check the following issues:

- https://github.com/mateuszmarkowski/jQuery-Seat-Charts/issues/39
- https://github.com/mateuszmarkowski/jQuery-Seat-Charts/issues/31

**Comment by marcosicp** [comment]
thanks! @mateuszmarkowski !
