### ISSUE TITLE
Not an issue just wondered

### ISSUE THREAD

**Issue by tanmuhittin** [mateuszmarkowski/jQuery-Seat-Charts#5]
I am trying to make a system that user can create the sitting plan.
For that user enters the dimension. Then I want the user to be able to add/delete vertical or horizontal row. For that I wrote

[code]
$('.horizontal-row-delete-button').click(function(e){
                    map.shift();
                    console.log(map);
                    $('#seat-map').html('');
                    sc = $('#seat-map').seatCharts({map:map.shift(),seats:seats,naming:naming,legend:legend});
                });
[/code]

But this code doesnt reload the sitting plan.
Do you have any idea why

By the way very good job. Thanks a lot

**Comment by kirantpatil** [comment]
@mateuszmarkowski, any updates on dynamic maps ?

**Comment by mateuszmarkowski** [comment]
@kirantpatil No progress yet.
