### ISSUE TITLE
Multiple Pricing Options Per Seat

### ISSUE THREAD

**Issue by envywebsites** [mateuszmarkowski/jQuery-Seat-Charts#50]
Hi there

Enjoying experimenting with this plugin so far, really simple implementation of a much needed UI with so many uses!

I wondered how easy it might be to have multiple options once a seat is selected?

So, for example, you could have an "Adult" in one seat and "Child" in another seat, they would each be priced differently?

Kind regards

Ben

**Comment by mateuszmarkowski** [comment]
It should be pretty easy to implement. Every seat has a hash with custom data where you can include your pricing options. This way when a user clicks on a seat, you can read the hash to see what pricing options are available for the seat.

You just have to take care of the visual side of the selection by i.e. presenting options in a dropdown or a pop-up.

**Comment by envywebsites** [comment]
Thanks Mateusz, that’s really useful.

 

I managed to get this working with a dropdown as you suggested and it works great!

**Comment by ngethe** [comment]
Please share how you did it @envywebsites
