### ISSUE TITLE
how to insert selected data mysql db with php

### ISSUE THREAD

**Issue by nexpo** [mateuszmarkowski/jQuery-Seat-Charts#52]
i am new in  jquery and ajax .any help will be appreciated. thanks in advance. great wok!

**Comment by XDRosenheim** [comment]
Maybe you could explain what you need help with....?

**Comment by XDRosenheim** [comment]
I have been using this in a project if you want to have a look around.  
https://github.com/HLPF/Website-2017/tree/master/Include  
It uses MySQL an php...

**Comment by giumazzi** [comment]
@nexpo have You found any help?

**Comment by giumazzi** [comment]
I'have found this!
[http://stackoverflow.com/questions/35365435/get-variables-from-javascript-and-build-a-sql-query-on-php-for-jquery-seat-chart](url)
I think it is very usefull
If you are working in a project please contact me at ilguittobook at gmail dot com
