### ISSUE TITLE
Seat numbering

### ISSUE THREAD

**Issue by mtavira** [mateuszmarkowski/jQuery-Seat-Charts#53]
I can see the seats have a number increasing from 1 till the number of seats. However airlines dont number the seats like that. The number the columns {window} A, B, C {aisle} D, E, F {window} and so on on bigger planes and then the rows by number. So in you example (http://jsc.mm-lamp.com/) it would be: 
1A 1B {aisle} 1C 1D
2A 2B {aisle} 2C 2D
.....
Some airlines number this differently (they skip the "B" and "E" middle seats on 4 per row airplanes):
1A 1C {aisle} 1D 1F
2A 2C {aisle} 2D 3F
3A 3C {aisle} 3D 3F

Is there a way we can achieve this numbering?

Thanks,

moises.

**Comment by mtavira** [comment]
Ok, found the answer with naming columns "A", "B", "C" .... and changing the getId method to return row+column. Thanks just needed a little reseach.

Great work!!!

**Comment by jaycer17** [comment]
Hi, can you share your fix here @mtavira? Thank you!
