### ISSUE TITLE
Seat Naming Issue

### ISSUE THREAD

**Issue by MostafaAttia** [mateuszmarkowski/jQuery-Seat-Charts#54]
I have seats named as characters from A to Z, But also have some seats which are named like: AA, AB, AC and so on.

When I name a seat in two characters like AA or AB, The layout for these seats is broken and an empty seat (with no label or id) is shown after each seat, like  shown in this [screenshot](http://imgur.com/a/06HoH) !

I tried to change the name to A_A or _A_A but it didn't work.

Any idea where is the problem ?

**Comment by mateuszmarkowski** [comment]
It's most likely a CSS issue but I'm not able to replicate it. The demo layout doesn't break even if I replace labels with much longer ones:
![image](https://cloud.githubusercontent.com/assets/5392286/24389959/daaf4e64-1385-11e7-9952-e920d8ea72db.png)

Labels are truncated but this is expected as there isn't enough room for them.

What was the browser/version?

**Comment by MostafaAttia** [comment]
@mateuszmarkowski  I think the problem isn't a CSS issue, the problem is with generating the seats with more than one character, for example: 

`seats: {
			a: {
				price   : 99.99,
				classes : 'front-seat' 
			},
                       b: {
				price   : 50.99,
				classes : 'b-seat' 
			},
                       c: {
				price   : 40.99,
				classes : 'c-seat'
			},
                       .
                       .
                       .
                       z: {
				price   : 30.99,
				classes : 'z-seat' 
			},

                       ab: {      // here is the problem
				price   : 20.99,
				classes : 'ab-seat' 
			},
		
		}`

**Comment by mateuszmarkowski** [comment]
Right, now I see. Seat identifier (AKA character) can only be a single character. If you need a longer name, you can include it in your custom data hash, i.e.:

```javascript
a: {
    price: 20.50,
    class: 'ab-seat',
    name: 'AB'
}
```

**Comment by ArkadySladkoff** [comment]
so we have only 26 rows for seats?

**Comment by mateuszmarkowski** [comment]
Only if you want to use a different character for each row. Generally characters are intended for seat classes so 26 should be enough in most cases.
