### ISSUE TITLE
How to have seat numbering vertical instead of horizontal?

### ISSUE THREAD

**Issue by xithalius** [mateuszmarkowski/jQuery-Seat-Charts#58]
How can i turn:
1    2   3   4
5    6   7   8
9   10 11 12
13 14 15 16

Into:
1  5  9    13
2  6  10  14
3  7  11  15
4  8  12  16

**Comment by mateuszmarkowski** [comment]
You will have to override the default implementation of [getLabel](https://github.com/mateuszmarkowski/jQuery-Seat-Charts#naming). GetLabel is responsible for generating labels.

**Comment by sugoireed** [comment]
> You will have to override the default implementation of [getLabel](https://github.com/mateuszmarkowski/jQuery-Seat-Charts#naming). GetLabel is responsible for generating labels.

I've figured out how to override. Any pointers on how to get the actual numbers?
