### ISSUE TITLE
Skip counting ID of empty rows/column

### ISSUE THREAD

**Issue by hihahihahoho** [mateuszmarkowski/jQuery-Seat-Charts#62]
For Ex i have a map like this:
  map: ['[empty][empty][empty]nnnnnnnnnnnnnnnn[empty][empty][empty]']
eventhough the first three spaces of the map are empty, they are still counted [A_1, A_2, A_3], so the first 'n' ID is [A_4], I want them to start counting at the first 'n' seat (n[A_1]), not emty space. Any solution for this?

**Comment by mateuszmarkowski** [comment]
What you can in your situation is simply overriding [getLabel / getId ](https://github.com/mateuszmarkowski/jQuery-Seat-Charts#naming) so that your functions skip empty spaces.

**Comment by hihahihahoho** [comment]
ok, thanks man 👍

**Comment by jaycer17** [comment]
@mateuszmarkowski can you please give example on how to override the getLabel / getId?

**Comment by ilrisa** [comment]
hi, I agree with the request made by Jaycer17, can i have an example of how to set the functions GetLabel and GetId? Thank you
