### ISSUE TITLE
More characters available

### ISSUE THREAD

**Issue by etesin10** [mateuszmarkowski/jQuery-Seat-Charts#64]
it needs more chars available, what if the user creates the classes and legends dinamically there would be a limit of 62 classes , as an example  they could use this in a call center , where campaigns and figures are.

if you want to see a whole campaign as one color but still able to identify if its a manager , coordinator , supervisor etc ect  through the label , then a style would have to be made for each campaign and figure, if there is a lot of campaigns , they would have to limit the types to 62

from a to z and from A to Z and from 1 to 0 it would be cool that the class could accept more than that , receiving chars such as ñ,é,ë,etc etc that would add at least 20 more style possibilities

**Comment by mateuszmarkowski** [comment]
I'm not sure if adding just a couple more characters makes a significant difference, the number of possibilities will remain low anyway. Perhaps there's a better way to address this use case with e.g. multiple maps or assigning attributes to individual seats.

You could use a different set of CSS rules for each seat(ID) and JSC makes it very easy for you to control ID generation so you could have a unique color for every seat if you so wish.
